apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: muellners.azurecr.io/bounties:latest
      context: ../bounties
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
