apiVersion: v1
kind: PersistentVolume
metadata:
  name: bounties-kafka-pv
  labels:
    app: bounties
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bounties-kafka-pvc
  labels:
    app: bounties
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany

---

apiVersion: v1
kind: Service
metadata:
  name: bounties-zookeeper
  labels:
    app: bounties
spec:
  selector:
    app: bounties
    tier: kafka
  ports:
  - port: 2181
    targetPort: 2181

---

apiVersion: v1
kind: Service
metadata:
  name: bounties-kafka
  labels:
    app: bounties
spec:
  selector:
    app: bounties
    tier: kafka
  ports:
  - port: 9092
    targetPort: 9092

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bounties-zookeeper
  labels:
    app: bounties
spec:
  selector:
    matchLabels:
      app: bounties
  template:
    metadata:
      labels:
        app: bounties
    spec:
      containers:
      - name: bounties-zookeeper
        image: confluentinc/cp-zookeeper:5.5.2
        resources:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "6Gi"
            cpu: "2000m"
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        ports:
        - containerPort: 2181
        volumeMounts:
          - name: bounties-kafka-persistent-storage
            mountPath: /opt/zookeeper/data
            subPath: data
      volumes:
        - name: bounties-kafka-persistent-storage
          persistentVolumeClaim:
            claimName: bounties-kafka-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bounties-kafka
  labels:
    app: bounties
spec:
  selector:
    matchLabels:
      app: bounties
  template:
    metadata:
      labels:
        app: bounties
    spec:
      containers:
      - name: bounties-kafka
        image: confluentinc/cp-kafka:5.5.2
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "5Gi"
            cpu: "2000m"
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: bounties-zookeeper:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://bounties-kafka:29092,PLAINTEXT_HOST://bounties-kafka:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        ports:
        - containerPort: 9092
