apiVersion: v1
kind: PersistentVolume
metadata:
  name: bounties-mysql-pv
  labels:
    app: bounties
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bounties-mysql-pvc
  labels:
    app: bounties
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany

---

apiVersion: v1
kind: Service
metadata:
  name: bounties-mysql
  labels:
    app: bounties
spec:
  selector:
    app: bounties
    tier: mysql
  ports:
  - port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bounties-mysql
  labels:
    app: bounties
spec:
  selector:
    matchLabels:
      app: bounties
  template:
    metadata:
      labels:
        app: bounties
    spec:
      containers:
      - name: bounties-mysql
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "5Gi"
            cpu: "2000m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          # value: mysql
          valueFrom:
            secretKeyRef:
              name: bounties-mysql-db-secret
              key: password
        livenessProbe:
          exec:
            command: ["sh", "-c", "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}"]
          failureThreshold: 10
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["sh", "-c", "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD}"]
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 3306
          name: bounties-mysql
        volumeMounts:
          - name: bounties-mysql-initdb
            mountPath: /docker-entrypoint-initdb.d/
          - name: bounties-mysql-persistent-storage
            mountPath: /var/lib/mysql
            subPath: mysql
      volumes:
        - name: bounties-mysql-initdb
          configMap:
            name: bounties-mysql-initdb
        - name: bounties-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: bounties-mysql-pvc
