apiVersion: v1
kind: Service
metadata:
  name: bounties-keycloak
  labels:
    app: bounties
spec:
  selector:
    app: bounties
    tier: keycloak
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bounties-keycloak
  labels:
    app: bounties
spec:
  selector:
    matchLabels:
      app: bounties
  template:
    metadata:
      labels:
        app: bounties
    spec:
      containers:
      - name: bounties-keycloak
        image: jboss/keycloak:10.0.0
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "5Gi"
            cpu: "2000m"
        env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
          # valueFrom:
          #   secretKeyRef:
          #     name: bounties-keycloak-db-secret
          #     key: password
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: h2
        args:
          - -b
          - 0.0.0.0
          - -Dkeycloak.migration.action=import
          - -Dkeycloak.migration.provider=dir
          - -Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config
          - -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
          - -Djboss.socket.binding.port-offset=1000
          - -Dkeycloak.profile.feature.upload_scripts=enabled
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        volumeMounts:
          - name: realm-config
            mountPath: /opt/jboss/keycloak/realm-config
      volumes:
        - name: realm-config
          configMap:
            name: realm-config
            