apiVersion: v1
kind: Service
metadata:
  name: bounties
  namespace: default
  labels:
    app: bounties
spec:
  selector:
    app: bounties
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
