apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bounties-mysql-pvc
  labels:
    app: bounties
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bounties-mysql
  labels:
    app: bounties
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bounties
      tier: mysql
  template:
    metadata:
      labels:
        app: bounties
        tier: mysql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bounties-mysql-pvc
      containers:
        - name: bounties-mysql
          image: mysql:5.7
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: mysql
              # valueFrom:
              #   secretKeyRef:
              #     name: bounties-mysql-secret
              #     key: password
            - name: MYSQL_DATABASE
              value: bounties
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
              name: bounties-mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: mysql
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          livenessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}"]
            failureThreshold: 10
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command: ["sh", "-c", "mysqladmin ping -uroot -p${MYSQL_ROOT_PASSWORD}"]
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bounties
  name: bounties-mysql
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: bounties
    tier: mysql
  clusterIP: None
