apiVersion: v1
kind: ConfigMap
metadata:
  name: bounties-mysql-initdb
  labels:
    app: bounties
data:
  init.sql: |
    # create databases
    CREATE DATABASE IF NOT EXISTS `bounties`;
    CREATE DATABASE IF NOT EXISTS `keycloak`;

    # create root user and grant rights
    GRANT ALL ON *.* TO 'root'@'%';
