name: Azure Container Registry Login and Push

on:
  push:
    branches: [master]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: muellners.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build --build-arg JAR_FILE=build/libs/\*.jar -t muellners.azurecr.io/bounties:latest .
        docker push muellners.azurecr.io/bounties:latest
